const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
let browser;
async function main(){
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||'/tmp/chromium',headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));let requests=[];
 const row={open_time_ms:1700000000000,open_time_utc:'2023-11-14T22:13:20Z',open:100,high:110,low:95,close:105,volume:12.5,taker_buy_volume:4,closed:true};
 let currentRow=row;
 await page.route('http://market.test/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/'){const file=path.resolve(__dirname,'../market_data/template.html');return route.fulfill({contentType:'text/html',body:fs.existsSync(file)?fs.readFileSync(file,'utf8'):'<!doctype html><title>not implemented</title>'});}requests.push(u.pathname+u.search);const market=u.searchParams.get('market');if(u.pathname==='/api/catalog')return route.fulfill({json:{ok:true,market,source:'fixture '+market,requested_at_utc:'2026-10-04T00:00:00Z',http_status:200,instruments:[{symbol:market==='us_equity'?'AAPL':'SOLUSDT',name:market==='us_equity'?'Apple':'Solana',venue:market,provider_symbol:market==='us_equity'?'AAPL':'SOLUSDT'},{symbol:'SECOND',name:'另一个品种',venue:market,provider_symbol:'SECOND'}],request_count:1,partial:false,warnings:[],error:null}});if(u.pathname==='/api/candles'){if(market==='binance_spot')await new Promise(resolve=>setTimeout(resolve,350));return route.fulfill({json:{ok:market!=='gate_usdt',market,source:'fixture '+market,symbol:u.searchParams.get('symbol'),interval:u.searchParams.get('interval'),requested_count:Number(u.searchParams.get('limit')),requested_at_utc:'2026-10-04T00:00:00Z',received_at_utc:'2026-10-04T00:00:01Z',http_status:market==='gate_usdt'?503:200,source_url:'https://example.test/market',volume_unit:'base asset',rows:market==='gate_usdt'?[]:[{...currentRow,taker_buy_volume:market==='binance_spot'?4:null}],dropped_rows:0,request_count:1,partial:false,warnings:[],error:market==='gate_usdt'?'UPSTREAM_UNAVAILABLE':null}});}return route.fulfill({status:404,body:'not found'});});
 await page.goto('http://market.test/');
 assert.equal(await page.locator('#market-select').count(),1,'The market selector must expose the full market catalog.');
 await page.waitForFunction(()=>document.querySelectorAll('#instrument-select option').length===2);
 assert.equal(await page.locator('#market-select option').count(),8,'Eight catalog markets must remain selectable.');
 assert.equal(requests.filter(x=>x.startsWith('/api/candles')).length,0,'Catalog loading must not automatically fetch candles.');
 await page.locator('#instrument-search').fill('SECOND');
 assert.equal(await page.locator('#instrument-select option').count(),1,'Search filters instruments from the full returned catalog.');
 await page.locator('#instrument-select').selectOption('SECOND');await page.locator('#fetch-candles').click();
 await page.locator('#market-select').selectOption('us_equity');
 await page.waitForFunction(()=>document.querySelector('#instrument-select').value==='AAPL');
 await page.waitForTimeout(500);
 assert.equal(await page.locator('#candle-body tr[data-candle]').count(),0,'A response from an old market must never populate the new market view.');
 await page.locator('#limit-input').fill('100000');await page.locator('#interval-select').selectOption('15m');await page.locator('#fetch-candles').click();
 await page.waitForFunction(()=>document.querySelectorAll('#candle-body tr[data-candle]').length===1);
 assert.match(requests.at(-1),/limit=100000/);assert.match(requests.at(-1),/interval=15m/);
 assert.match(await page.locator('#result-title').innerText(),/AAPL/);
 assert.match(await page.locator('#candle-body').innerText(),/105/);
 assert.equal(await page.locator('#taker-value').innerText(),'未提供','Non-A sources cannot invent taker-buy volume.');
 currentRow={...row,open:1e-12,high:1.1e-12,low:9.5e-13,close:1.05e-12};
 await page.locator('#fetch-candles').click();
 await page.waitForFunction(()=>document.querySelector('#fetch-status').dataset.state==='ready');
 const numeric=s=>Number(s.replace(/,/g,''));
 assert.equal(numeric(await page.locator('#close-value').innerText()),1.05e-12,'A nonzero tiny close must not be formatted as zero.');
 assert.equal(numeric(await page.locator('#candle-body tr[data-candle] td').nth(4).innerText()),1.05e-12,'The exact same tiny close must stay nonzero in the ledger.');
 assert.match(await page.locator('#chart-readout').innerText(),/C 1\.05e-12/,'Chart readout must retain the tiny close value.');
 const ticks=(await page.locator('#candle-chart text').allTextContents()).slice(0,4).map(numeric);
 assert.ok(ticks.every(v=>Number.isFinite(v)&&v>0),'Positive tiny price-axis ticks must not collapse to zero.');
 await page.locator('#market-select').selectOption('gate_usdt');await page.waitForFunction(()=>document.querySelector('#instrument-select').value==='SOLUSDT');await page.locator('#fetch-candles').click();
 await page.waitForFunction(()=>document.querySelector('#fetch-status').dataset.state==='error');
 assert.equal(await page.locator('#candle-body tr[data-candle]').count(),0,'Failed requests must clear prior successful prices.');
 assert.match(await page.locator('#taker-note').innerText(),/来源B没有主动买量/);
 await page.setViewportSize({width:320,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'The 320px viewport must not overflow.');
 assert.deepEqual(errors,[]);await factorWorkflow(browser);await browser.close();console.log('PASS: 8 catalogs, instrument search, manual fetch, 100000/15m request, response races, null taker, failure clearing, tiny nonzero prices and axes, 320px, no JS errors.');
}
async function factorWorkflow(browser){
 const {spawn}=require('node:child_process'),os=require('node:os');
 const root=path.resolve(__dirname,'..'),temporary=fs.mkdtempSync(path.join(os.tmpdir(),'qd-factor-browser-'));
 const child=spawn(path.join(root,'.venv/bin/python'),[path.join(__dirname,'factor_browser_server.py'),path.join(temporary,'factors.sqlite')],{cwd:root,stdio:['ignore','pipe','pipe']});
 let diagnostics='';child.stderr.on('data',data=>diagnostics+=data.toString());
 try{
  const port=await new Promise((resolve,reject)=>{let data='';const timeout=setTimeout(()=>reject(new Error('Synthetic server did not start: '+diagnostics)),15000);child.once('exit',code=>{clearTimeout(timeout);reject(new Error('Synthetic server exited '+code+': '+diagnostics));});child.stdout.on('data',chunk=>{data+=chunk.toString();if(/^[0-9]+\n/.test(data)){clearTimeout(timeout);resolve(Number(data.trim()));}});});
  const origin='http://127.0.0.1:'+port,page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[],writes=[];
  page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.method()==='POST')writes.push(request.url());});
  await page.addInitScript(()=>{
   const original=File.prototype.text;window.factorReadControls=new Map();
   File.prototype.text=function(){const result=original.call(this);if(!this.name.startsWith('delayed-'))return result;
    let resolve;const pending=new Promise(yes=>{resolve=yes;});
    window.factorReadControls.set(this.name,{release:async()=>resolve(await result)});return pending;};
  });
  await page.goto(origin+'/factors');
  await page.waitForSelector('#factor-select option[value="minute.vwap60@1.0.0"]');
  assert.equal(await page.locator('#factor-select option').count(),16,'The catalog has exactly nine bound definitions and seven locked components.');
  await page.locator('#factor-select').selectOption('locked.amihud@1.0.0');
  await page.waitForFunction(()=>document.querySelector('#evidence-status').textContent.includes('无本次观测'));
  assert.equal(await page.locator('#evidence-list [data-observation]').count(),0,'Unimplemented components must never invent observations.');
  await page.waitForFunction(()=>document.querySelector('#trial-list').textContent.includes('No recorded trials'));
  assert.match(await page.locator('#lifecycle-list').innerText(),/No recorded lifecycle transitions/);
  assert.match(await page.locator('#history-status').innerText(),/candidate/);
  await page.locator('#factor-select').selectOption('minute.vwap60@1.0.0');
  await page.waitForSelector('#evidence-list [data-observation]');
  assert.match(await page.locator('#evidence-list').innerText(),/202.25/);
  assert.match(await page.locator('#evidence-list').innerText(),/EXPIRED_QUALITY/);
  assert.match(await page.locator('#evidence-list').innerText(),/Age|年龄/);
  const fields=['instrument_id','observed_at','source_published_at','provider_available_at','value','unit','factor_id','factor_version'];
  const headers=['Asset','Observed','Published','ProviderTime','Result','Units','Factor','Version'];
  const row=['SYNTH','2026-10-06T12:00:00Z','2026-10-06T12:00:01Z','2026-10-06T12:00:02Z','10.5','ratio','external.browser_value','1'];
  const definition={ref:{factor_id:'external.browser_value',version:'1'},name:'<img src=x onerror="window.factorXss=true">',purpose:'Synthetic browser acceptance',market:'us_equity',frequency:'daily',unit:'ratio',formula_text:'External value; no code executed',calculator_key:null,input_fields:['value'],min_history:{bars:1},missing_policy:'Preserve missing',window:{bars:1},lag:{bars:0},direction:'descriptive'};
  const document={definition,manifest:{dataset_id:'browser-synthetic-import',version:1,source_ref:'synthetic browser source',universe_version:'browser-synthetic-v1',adjustment:'unadjusted',provider:'synthetic',permission_basis:'synthetic fixture',source_timezone:'UTC',corporate_action_basis:'not applicable',history_version:'synthetic-v1',coverage_gaps:[]}};
  const upload=async(values)=>{
   await page.locator('#csv-file').setInputFiles({name:'synthetic.csv',mimeType:'text/csv',buffer:Buffer.from(headers.join(',')+'\n'+values.join(',')+'\n')});
   await page.locator('#definition-file').setInputFiles({name:'definition.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(document))});
   await page.waitForSelector('#mapping-instrument_id option[value="Asset"]');
   for(let i=0;i<fields.length;i++)await page.locator('#mapping-'+fields[i]).selectOption(headers[i]);
  };
  const bad=[...row];bad[0]='UNKNOWN';bad[4]='NaN';await upload(bad);
  await page.locator('#preview-import').click();
  await page.waitForFunction(()=>document.querySelector('#preview-status').dataset.state==='error');
  assert.match(await page.locator('#preview-errors').innerText(),/Row 2|第 2 行/);
  assert.match(await page.locator('#preview-errors').innerText(),/UNKNOWN_INSTRUMENT|INVALID_FACTOR_VALUE/);
  assert.ok(await page.locator('#save-import').isDisabled());assert.equal(writes.filter(url=>url.endsWith('/commit')).length,0);
  await upload(row);await page.locator('#preview-import').click();
  await page.waitForFunction(()=>document.querySelector('#preview-status').dataset.state==='ready');
  // Hold real File.text() completions to expose replacement/read ordering.
  for(const kind of ['csv','definition']){
   const filename='delayed-replacement-'+kind,input=kind==='csv'?'#csv-file':'#definition-file';
   const buffer=Buffer.from(kind==='csv'?headers.join(',')+'\n'+row.join(',')+'\n':JSON.stringify(document));
   await page.locator(input).setInputFiles({name:filename,mimeType:kind==='csv'?'text/csv':'application/json',buffer});
   await page.waitForFunction(name=>window.factorReadControls.has(name),filename);
   assert.ok(await page.locator('#preview-import').isDisabled(),kind+' replacement disables preview during read');
   assert.ok(await page.locator('#save-import').isDisabled(),kind+' replacement invalidates old preview');
   await page.evaluate(()=>document.querySelector('#save-import').click());
   assert.equal(writes.filter(url=>url.endsWith('/commit')).length,0);
   await page.evaluate(async name=>await window.factorReadControls.get(name).release(),filename);
   if(kind==='csv')for(let i=0;i<fields.length;i++)await page.locator('#mapping-'+fields[i]).selectOption(headers[i]);
   await page.waitForFunction(()=>!document.querySelector('#preview-import').disabled);
   assert.ok(await page.locator('#save-import').isDisabled(),'Replacement completion needs a fresh preview');
   await page.locator('#preview-import').click();
   await page.waitForFunction(()=>document.querySelector('#preview-status').dataset.state==='ready');
   const oldName='delayed-old-'+kind;
   const oldBuffer=Buffer.from(kind==='csv'?headers.join(',')+'\n'+bad.join(',')+'\n':JSON.stringify({...document,definition:{...definition,name:'Late stale definition',ref:{factor_id:'external.stale_discard',version:'1'}}}));
   await page.locator(input).setInputFiles({name:oldName,mimeType:kind==='csv'?'text/csv':'application/json',buffer:oldBuffer});
   await page.waitForFunction(name=>window.factorReadControls.has(name),oldName);
   await page.locator(input).setInputFiles({name:'latest-'+kind,mimeType:kind==='csv'?'text/csv':'application/json',buffer});
   if(kind==='csv')for(let i=0;i<fields.length;i++)await page.locator('#mapping-'+fields[i]).selectOption(headers[i]);
   await page.waitForFunction(()=>!document.querySelector('#preview-import').disabled);
   await page.evaluate(async name=>await window.factorReadControls.get(name).release(),oldName);
   await page.locator('#preview-import').click();
   await page.waitForFunction(()=>document.querySelector('#preview-status').dataset.state==='ready');
   assert.match(await page.locator('#preview-samples').innerText(),/SYNTH/);
   assert.match(await page.locator('#preview-samples').innerText(),/external.browser_value/);
   assert.ok(await page.locator('#save-import').isEnabled());
  }
  assert.equal(await page.locator('#definition-name').textContent(),definition.name);
  assert.equal(await page.locator('#definition-name img').count(),0);
  assert.equal(await page.evaluate(()=>window.factorXss),undefined);
  assert.equal(writes.filter(url=>url.endsWith('/commit')).length,0,'Preview must never save automatically.');
  const session=await page.evaluate(async()=>await (await fetch('/api/factors/session')).json());
  const downloadEvent=page.waitForEvent('download');await page.locator('#download-evidence').click();const download=await downloadEvent;
  const downloaded=fs.readFileSync(await download.path(),'utf8');
  assert.ok(!downloaded.includes(session.csrf_token));assert.ok(!downloaded.includes('csrf_token'));
  assert.ok(!downloaded.includes('csv_text'));assert.match(downloaded,/content_hash/);
  await page.locator('#save-import').click();
  await page.waitForFunction(()=>document.querySelector('#commit-status').dataset.state==='ready');
  await page.waitForFunction(()=>document.querySelector('#factor-select').value==='external.browser_value@1');
  await page.waitForSelector('#evidence-list [data-observation]');
  assert.match(await page.locator('#evidence-list').innerText(),/10.5/);
  assert.match(await page.locator('#evidence-list').innerText(),/EXTERNAL_VALUES_UNVERIFIED|PIT_EVIDENCE_REQUIRED/);
  assert.equal(await page.locator('#evidence-list img').count(),0);
  assert.equal(writes.filter(url=>url.endsWith('/commit')).length,1,'Save requires one explicit click.');
  await page.locator('#factor-select').selectOption('minute.vwap60@1.0.0');await page.waitForSelector('#evidence-list [data-observation]');
  const screenshots=path.join(root,'.superpowers/sdd/quant-factor-foundations-implementation-plan-20261006/task-7-screenshots');fs.mkdirSync(screenshots,{recursive:true});
  await page.screenshot({path:path.join(screenshots,'factor-catalog-evidence-desktop.png'),fullPage:true});
  await page.setViewportSize({width:320,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Factor import page fits 320px.');
  await page.screenshot({path:path.join(screenshots,'factor-import-mobile.png'),fullPage:true});
  assert.deepEqual(errors,[]);await page.close();
  console.log('PASS: dot cloud browser, real loopback synthetic import, mapping, row errors/no save, explicit preview/save/evidence, HTML-like text, token-free metadata download, no fake components, stale evidence, 320px, no JS errors.');
 }finally{
  child.kill('SIGTERM');await new Promise(resolve=>{if(child.exitCode!==null)return resolve();child.once('exit',resolve);});fs.rmSync(temporary,{recursive:true,force:true});
 }
}
main().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
