const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
let browser;
async function main(){
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||'/tmp/chromium',headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));let requests=[];
 const row={open_time_ms:1700000000000,open_time_utc:'2023-11-14T22:13:20Z',open:100,high:110,low:95,close:105,volume:12.5,taker_buy_volume:4,closed:true};
 let currentRow=row;
 await page.route('http://market.test/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/'){const file=path.resolve(__dirname,'../market_data/template.html');return route.fulfill({contentType:'text/html',body:fs.existsSync(file)?fs.readFileSync(file,'utf8'):'<!doctype html><title>not implemented</title>'});}requests.push(u.pathname+u.search);const market=u.searchParams.get('market');if(u.pathname==='/api/catalog')return route.fulfill({json:{ok:true,market,source:'fixture '+market,requested_at_utc:'2026-10-04T00:00:00Z',http_status:200,instruments:[{symbol:market==='us_equity'?'AAPL':'SOLUSDT',name:market==='us_equity'?'Apple':'Solana',venue:market,provider_symbol:market==='us_equity'?'AAPL':'SOLUSDT'},{symbol:'SECOND',name:'另一个品种',venue:market,provider_symbol:'SECOND'}],request_count:1,partial:false,warnings:[],error:null}});if(u.pathname==='/api/candles'){if(market==='binance_spot')await new Promise(resolve=>setTimeout(resolve,350));return route.fulfill({json:{ok:market!=='gate_usdt',market,source:'fixture '+market,symbol:u.searchParams.get('symbol'),interval:u.searchParams.get('interval'),requested_count:Number(u.searchParams.get('limit')),requested_at_utc:'2026-10-04T00:00:00Z',received_at_utc:'2026-10-04T00:00:01Z',http_status:market==='gate_usdt'?503:200,source_url:'https://example.test/market',volume_unit:'base asset',rows:market==='gate_usdt'?[]:[{...currentRow,taker_buy_volume:market==='binance_spot'?4:null}],dropped_rows:0,request_count:1,partial:false,warnings:[],error:market==='gate_usdt'?'UPSTREAM_UNAVAILABLE':null}});}return route.fulfill({status:404,body:'not found'});});
 await page.goto('http://market.test/');
 assert.equal(await page.locator('#market-select').count(),1,'The market selector must expose the full market catalog.');
 await page.waitForFunction(()=>document.querySelectorAll('#instrument-select option').length===2);
 assert.equal(await page.locator('#market-select option').count(),8,'Eight catalog markets must remain selectable.');
 assert.equal(requests.filter(x=>x.startsWith('/api/candles')).length,0,'Catalog loading must not automatically fetch candles.');
 await page.locator('#instrument-search').fill('SECOND');
 assert.equal(await page.locator('#instrument-select option').count(),1,'Search filters instruments from the full returned catalog.');
 await page.locator('#instrument-select').selectOption('SECOND');await page.locator('#fetch-candles').click();
 await page.locator('#market-select').selectOption('us_equity');
 await page.waitForFunction(()=>document.querySelector('#instrument-select').value==='AAPL');
 await page.waitForTimeout(500);
 assert.equal(await page.locator('#candle-body tr[data-candle]').count(),0,'A response from an old market must never populate the new market view.');
 await page.locator('#limit-input').fill('100000');await page.locator('#interval-select').selectOption('15m');await page.locator('#fetch-candles').click();
 await page.waitForFunction(()=>document.querySelectorAll('#candle-body tr[data-candle]').length===1);
 assert.match(requests.at(-1),/limit=100000/);assert.match(requests.at(-1),/interval=15m/);
 assert.match(await page.locator('#result-title').innerText(),/AAPL/);
 assert.match(await page.locator('#candle-body').innerText(),/105/);
 assert.equal(await page.locator('#taker-value').innerText(),'未提供','Non-A sources cannot invent taker-buy volume.');
 currentRow={...row,open:1e-12,high:1.1e-12,low:9.5e-13,close:1.05e-12};
 await page.locator('#fetch-candles').click();
 await page.waitForFunction(()=>document.querySelector('#fetch-status').dataset.state==='ready');
 const numeric=s=>Number(s.replace(/,/g,''));
 assert.equal(numeric(await page.locator('#close-value').innerText()),1.05e-12,'A nonzero tiny close must not be formatted as zero.');
 assert.equal(numeric(await page.locator('#candle-body tr[data-candle] td').nth(4).innerText()),1.05e-12,'The exact same tiny close must stay nonzero in the ledger.');
 assert.match(await page.locator('#chart-readout').innerText(),/C 1\.05e-12/,'Chart readout must retain the tiny close value.');
 const ticks=(await page.locator('#candle-chart text').allTextContents()).slice(0,4).map(numeric);
 assert.ok(ticks.every(v=>Number.isFinite(v)&&v>0),'Positive tiny price-axis ticks must not collapse to zero.');
 await page.locator('#market-select').selectOption('gate_usdt');await page.waitForFunction(()=>document.querySelector('#instrument-select').value==='SOLUSDT');await page.locator('#fetch-candles').click();
 await page.waitForFunction(()=>document.querySelector('#fetch-status').dataset.state==='error');
 assert.equal(await page.locator('#candle-body tr[data-candle]').count(),0,'Failed requests must clear prior successful prices.');
 assert.match(await page.locator('#taker-note').innerText(),/来源B没有主动买量/);
 await page.setViewportSize({width:320,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'The 320px viewport must not overflow.');
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: 8 catalogs, instrument search, manual fetch, 100000/15m request, response races, null taker, failure clearing, tiny nonzero prices and axes, 320px, no JS errors.');
}
main().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
