const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
let browser;
const now=Date.now(), step=300000, end=Math.floor(now/step)*step;
function row(symbol,market='binance_spot',interval='5m',rank=1){return {market,source:market,symbol,interval,rank,status:'READY',reason:'全部规则通过',score:100,rule_id:'MINUTE_MA5_V1',price:112,price_unclosed:true,received_at_utc:new Date().toISOString(),requested_at_utc:new Date(Date.now()-140).toISOString(),signal_time_ms:end,request_duration_ms:140,http_status:200,source_url:'https://data-api.binance.vision/api/v3/klines',benchmark_symbol:'BTCUSDT',checks:[{key:'trend',label:'收盘价 > MA20（20根）',value:112,threshold:110,passed:true}],metrics:{ma5:111.8,closed_price:112,atr_pct:.4,distance_atr:.4,vwap60:111,return20_pct:1.8,rs20_pp:1.4,rvol20:2.5,vwap_basis:'quote/base'},bars:Array.from({length:80},(_,i)=>({open_time_ms:end-(80-i)*step,open:100+i*.1,high:100.2+i*.1,low:99.8+i*.1,close:100.1+i*.1,volume:20}))};}
async function main(){browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||'/tmp/chromium',headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});const page=await browser.newPage({acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));let cycle=0,calls=[],fail=false,forceStale=false,bulk=false;
await page.route('http://live.test/**',async route=>{const u=new URL(route.request().url()),q=u.searchParams,market=q.get('market')||'binance_spot',interval=q.get('interval')||'5m';calls.push(u.pathname+u.search);if(u.pathname==='/')return route.fulfill({contentType:'text/html',body:fs.readFileSync(path.resolve(__dirname,'../market_data/live.html'),'utf8')});if(u.pathname==='/api/live'){if(fail)return route.fulfill({status:502,json:{error:'fixture connection failure'}});if(market==='gate_usdt')await new Promise(r=>setTimeout(r,250));const symbols=market==='gate_usdt'?['BTC_USDT','ETH_USDT']:['BTCUSDT','ETHUSDT','SOLUSDT'];let rows=symbols.map((s,i)=>row(s,market,interval,i+1));rows[2]&&(rows[2].status='OUT');if(q.get('symbols'))rows=q.get('symbols').split(',').map((s,i)=>row(s,market,interval,i+1));if(bulk)rows=Array.from({length:240},(_,i)=>row('X'+String(i).padStart(3,'0')+'USDT',market,interval,i+1));if(forceStale)rows.forEach(r=>r.received_at_utc=new Date(Date.now()-100000).toISOString());return route.fulfill({json:{session_id:market+'-'+interval,config:Object.fromEntries(q),rule_id:'MINUTE_MA5_V1',source:market,state:'RUNNING',server_time_ms:Date.now(),cycle:++cycle,last_completed_ms:Date.now(),last_cycle_duration_seconds:1,next_refresh_seconds:10,rows,coverage:{universe:12,catalog_total:1000,scanned:rows.length,fresh:rows.length,batch_size:12,remaining_in_round:9,scope_note:'USDT计价分批',round:0},transitions:[{at_ms:Date.now(),symbol:rows[0].symbol,status:'READY',previous:'WATCH',reason:'确认通过'}]}});}if(u.pathname==='/api/live/detail')return route.fulfill({json:row(q.get('symbol'),q.get('session').includes('gate')?'gate_usdt':'binance_spot')});if(u.pathname==='/api/catalog')return route.fulfill({json:{ok:true,instruments:['BTCUSDT','ETHUSDT','TINYUSDT'].map(s=>({symbol:s,name:s}))}});if(u.pathname==='/api/live/history')return route.fulfill({json:{snapshots:[{at_ms:now-60000,cycle:1,config:{market:'binance_spot'},label:'HISTORICAL_OBSERVATION_BATCH',rows:[row('BTCUSDT')]}]}});return route.fulfill({status:404,body:'not found'});});
await page.goto('http://live.test/');await page.waitForSelector('#rows tr[data-symbol]');
assert.equal(await page.locator('h1').textContent(),'LIVE SCREENER');assert.equal(await page.locator('#rows tr[data-symbol]').count(),3);
await page.locator('#rows tr[data-symbol="ETHUSDT"] td').nth(4).click();assert.match(await page.locator('#detail h2').innerText(),/ETHUSDT/);assert.match(await page.locator('#detail .checks').innerText(),/110/, 'comparison threshold must be inspectable');await page.waitForFunction(()=>document.querySelectorAll('#chart rect').length===80);
await page.locator('#rows tr[data-symbol="SOLUSDT"]').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#detail h2').innerText(),'SOLUSDT');
await page.locator('[data-filter="OUT"]').click();assert.equal(await page.locator('#rows tr[data-symbol]').count(),1);await page.locator('[data-filter="ALL"]').click();
await page.locator('#quick-search').fill('ETH');assert.equal(await page.locator('#rows tr[data-symbol]').count(),1);await page.locator('#quick-search').fill('');
await page.locator('#pause').click();assert.equal(await page.locator('#rows .badge.READY').count(),0);assert.match(await page.locator('#feed-label').innerText(),/暂停/);const pausedCalls=calls.length;await page.waitForTimeout(2200);assert.equal(calls.length,pausedCalls);await page.locator('#pause').click();await page.waitForSelector('#rows .badge.READY');
const before=cycle;await page.waitForTimeout(2300);assert.ok(cycle>before,'polling must be continuous');
await page.locator('#market').selectOption('gate_usdt');await page.locator('#market').selectOption('binance_spot');await page.waitForTimeout(700);assert.equal(await page.locator('#rows tr[data-symbol="BTC_USDT"]').count(),0);
await page.locator('#band').fill('0.7');await page.locator('#apply').click();await page.waitForSelector('#rows tr[data-symbol]');assert.ok(calls.some(u=>u.includes('band=0.7')));
await page.locator('details.catalog summary').click();await page.locator('#catalog-load').click();await page.waitForSelector('[data-add="TINYUSDT"]');await page.locator('#catalog-search').fill('TINY');assert.equal(await page.locator('#catalog-results button').count(),1);await page.locator('[data-add="TINYUSDT"]').click();await page.waitForSelector('#rows tr[data-symbol="TINYUSDT"]');assert.ok(calls.some(u=>u.includes('symbols=TINYUSDT')));
const dl=page.waitForEvent('download');await page.locator('#export-csv').click();const csv=await dl;const dest='/tmp/qd-live-fixture.csv';await csv.saveAs(dest);assert.match(fs.readFileSync(dest,'utf8'),/MINUTE_MA5_V1/);
await page.locator('[data-nav="replay"]').click();await page.waitForFunction(()=>!document.querySelector('#replay-panel').hidden);assert.equal(await page.locator('#rows .badge.READY').count(),0);assert.match(await page.locator('#rows').innerText(),/历史/);await page.locator('#exit-replay').click();await page.waitForSelector('#rows .badge.READY');assert.ok(await page.locator('[data-nav=live]').evaluate(e=>e.classList.contains('active')),'returning to live must leave historical navigation');
forceStale=true;await page.waitForTimeout(2300);assert.equal(await page.locator('#rows .badge.READY').count(),0);assert.equal(await page.locator('#ready-count').innerText(),'0');forceStale=false;
fail=true;await page.waitForTimeout(2300);assert.equal(await page.locator('#rows .badge.READY').count(),0);assert.match(await page.locator('#banner').innerText(),/连接失败/);fail=false;
bulk=true;await page.waitForTimeout(2300);assert.equal(await page.locator('#rows tr[data-symbol]').count(),50,'large universes must paginate');assert.doesNotMatch(await page.locator('#detail').innerText(),/TINYUSDT/, 'removed symbols must not retain current detail');await page.locator('#next-page').click();assert.match(await page.locator('#rows').innerText(),/X050USDT/);await page.locator('#quick-search').fill('X239');assert.equal(await page.locator('#rows tr[data-symbol]').count(),1);await page.locator('#quick-search').fill('');for(const width of [320,768,1440]){await page.setViewportSize({width,height:950});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`no page overflow at ${width}`);}
await page.screenshot({path:'/tmp/qd-live-fixture.png',fullPage:true});assert.deepEqual(errors,[]);await browser.close();console.log('PASS LIVE: continuous polling, row/keyboard selection, OUT, search, pause, source race, thresholds, catalog/watchlist, CSV, replay, stale/offline demotion, 320/768/1440px, no JS errors.');}
main().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
